version: '3'

services:
  redis:
    image: redis
    restart: always
    container_name: 'demo_app_redis'
    command: redis-server
    ports:
      - '6379:6379'
  db:
    image: postgres
    container_name: 'demo_app_postgres'
    restart: always
    environment:
      POSTGRES_USER: adel
      POSTGRES_PASSWORD: DexJr57Xr83djNgsqlSMhTtr
      POSTGRES_DB: vitaminbd
    ports:
      - '54321:5432'
  web:
    build: .
    restart: always
    container_name: 'demo_app_django'
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - '8000:8000'
  celery:
    build: .
    container_name: 'demo_app_celery'
    command: celery -A app worker -l INFO
    volumes:
      - .:/app
    links:
      - redis
    depends_on:
      - web
      - redis
  celery-beat:
    build: .
    container_name: 'demo_app_celery_beat'
    command: celery -A app worker -l info -B
    volumes:
      - .:/app
    links:
      - redis
    depends_on:
      - web
      - redis
