# Generated by Django 4.2.3 on 2023-08-31 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vitamins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cartorder',
            name='track_number',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
