# Generated by Django 4.2.3 on 2023-09-05 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vitamins', '0004_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='address',
            field=models.CharField(max_length=250, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Статус платежа'),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='phone_number',
            field=models.BigIntegerField(null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='postal_code',
            field=models.CharField(max_length=20, verbose_name='Почтовый индекс'),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='track_number',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Трекномер'),
        ),
        migrations.AlterField(
            model_name='cartorderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='cartorderitem',
            name='qty',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='product',
            name='age',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='product',
            name='country',
            field=models.CharField(max_length=120, null=True, verbose_name='Страна производитель'),
        ),
        migrations.AlterField(
            model_name='product',
            name='dateCreation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='vitamins/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='В наличии'),
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Указ                                            ывать в том случае если хотите сделать скидку', max_digits=10, null=True, verbose_name='Старая цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='product',
            name='release_form',
            field=models.CharField(max_length=120, null=True, verbose_name='Форма выпуска'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='product',
            name='specifications',
            field=models.TextField(verbose_name='Состав'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=120, verbose_name='Название продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Название'),
        ),
    ]
