# Generated by Django 4.2.3 on 2023-09-20 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Vitamins', '0006_alter_cartorder_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vitamins.product'),
        ),
    ]
